# Generated by Django 2.2 on 2021-02-19 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=2000, verbose_name='Текст статьи')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('editing_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать в ленте')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25, verbose_name='Имя пользователя')),
                ('text', models.TextField(max_length=1000, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='app_news.NewsModel')),
            ],
        ),
    ]
