# Generated by Django 2.2 on 2021-02-28 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_newsmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new', to='app_news.NewsModel'),
        ),
    ]
