# Generated by Django 2.2 on 2021-03-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
