# Generated by Django 2.2 on 2021-03-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_auto_20210305_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Номер телефона', max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='card_number',
            field=models.CharField(blank=True, help_text='Номер скидочной карты', max_length=16, null=True, unique=True),
        ),
    ]
